#!/bin/bash

set -euo pipefail

# run from the script directory
cd "$(dirname "$0")"

echo "$(dirname "$0")"

replaceable=0
port=0
scorepolicy=0
env=0
seed="NONE"
runDir="run"
jvm_debug_port=0

while [ $# -gt 0 ]
do
    case "$1" in
        -replaceable) replaceable=1;;
        -port) port="$2"; shift;;
        -seed) seed="$2"; shift;;
        -scorepolicy) scorepolicy="$2"; shift;;
        -env) env=1;;
        -runDir) runDir="$2"; shift;;
        -jvm_debug_port) jvm_debug_port="$2"; shift;;
        *) echo >&2 \
            "usage: $0 [-replaceable] [-port 10000] [-seed 123123] [-scorepolicy 0123] [-env] [-runDir /home/asdasd] [-jvm_debug_port 1044]"
            exit 1;;
    esac
    shift
done
  
if ! [[ $port =~ ^-?[0-9]+$ ]]; then
    echo "Port value should be numeric"
    exit 1
fi


if [ \( $port -lt 0 \) -o \( $port -gt 65535 \) ]; then
    echo "Port value out of range 0-65535"
    exit 1
fi

if ! [[ $scorepolicy =~ ^-?[0-9]+$ ]]; then
    echo "Score policy should be numeric"
    exit 1
fi

# - - - - - - - - - - - - - - - - - -
# Validate jvm port (if any)
# - - - - - - - - - - - - - - - - - -
if ! [[ $jvm_debug_port =~ ^-?[0-9]+$ ]]; then
    echo "Port value should be numeric"
    exit 1
fi


if [ \( $jvm_debug_port -lt 0 \) -o \( $jvm_debug_port -gt 65535 \) ]; then
    echo "Port value out of range 0-65535"
    exit 1
fi

# - - - - - - - - - - - - - - - - - -

configDir="$runDir/config"

# Now write the configuration file
if [ ! -d "$configDir" ]; then
  mkdir "$configDir"
fi
echo "# Configuration file
# Autogenerated from command-line options

malmoports {
  I:portOverride=$port
}
malmoscore {
  I:policy=$scorepolicy
}

malmoseed {
  I:seed=$seed
}
" > "$configDir"/malmomodCLIENT.cfg

if [ $replaceable -gt 0 ]; then
    echo "runtype {
  B:replaceable=true
}
" >> "$configDir"/malmomodCLIENT.cfg
fi


if [ $env -gt 0 ]; then
    echo "envtype {
  B:env=true
}
" >> "$configDir"/malmomodCLIENT.cfg
fi

cat "$configDir"/malmomodCLIENT.cfg

echo "$runDir"

# ---- Launch Minecraft via the self-contained fat jar ----
# The shadowJar fat jar (MalmoMod-0.37.0-fat.jar) bundles the Malmo mod plus all
# of its runtime dependencies (Minecraft, Forge, launchwrapper, LWJGL, log4j,
# guava, etc.), so it can be launched directly with `java -jar`. The jar's
# Main-Class is com.microsoft.Malmo.Launcher.GradleStart, which sets up the SRG
# deobfuscation system properties, the default launch args (version, assetsDir,
# assetIndex, accessToken), the FMLTweaker tweak class, and appends the LWJGL
# natives to java.library.path — exactly what ForgeGradle's `runClient` does,
# but without invoking Gradle (so launches are fast and don't require network).
#
# This avoids the NoClassDefFoundError: LogManager crash that ForgeGradle's
# runClient hits when its assembled classpath is missing log4j.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MC_VER="1.11.2"

# The fat jar is normally pre-built in the source tree by the Python launcher
# (instance.py) and referenced via $MALMO_FAT_JAR. Fall back to a local copy
# (e.g. when this script is run manually) and build it via shadowJar if missing.
FAT_JAR="${MALMO_FAT_JAR:-$SCRIPT_DIR/build/libs/MalmoMod-0.37.0-fat.jar}"
if [ ! -f "$FAT_JAR" ]; then
    echo "Building MalmoMod fat jar via Gradle (first launch)..." >&2
    if ! ./gradlew shadowJar --stacktrace; then
        echo "ERROR: failed to build MalmoMod fat jar." >&2
        exit 1
    fi
    FAT_JAR="$SCRIPT_DIR/build/libs/MalmoMod-0.37.0-fat.jar"
fi

cd "$runDir"
# minecraftCacheDir tells GradleStartCommon where the Gradle Minecraft cache
# lives (GRADLE_USER_HOME is usually unset in batch mode, which would otherwise
# make its SRG path resolve to "null/..."). GradleStart.hackNatives() appends
# <cacheDir>/net/minecraft/natives/1.11.2 to java.library.path automatically.
JAVA_ARGS=(-Dfml.coreMods.load=com.microsoft.Malmo.OverclockingPlugin -Xmx2G -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant "-Dcom.microsoft.Malmo.GradleStartCommon.minecraftCacheDir=$HOME/.gradle/caches/minecraft/")
if [ "$jvm_debug_port" -gt 0 ]; then
    JAVA_ARGS=("-Xdebug" "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=$jvm_debug_port" "${JAVA_ARGS[@]}")
fi
declare -a cmd
cmd=(java "${JAVA_ARGS[@]}" -jar "$FAT_JAR")

if [ "${MINEDOJO_HEADLESS:-}" == "1" ]; then
  if ! command -v xvfb-run &> /dev/null; then
    echo "ERROR: xvfb-run not found but MINEDOJO_HEADLESS=1. Please install xvfb." >&2
    exit 1
  fi
  xvfb-run -a -s "-screen 0 1024x768x24" "${cmd[@]}"
else
  "${cmd[@]}"
fi
